services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_BASE_URL=http://php:80
    networks:
      - agri-spray-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  agri-spray-network:
    external: true