services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "80:3000"
      - "443:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_BASE_URL=https://api.agri-spray.com/api
    networks:
      - agri-spray-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agri-spray-network: