# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: prod
      SERVER_NAME: ${SERVER_NAME}
      MERCURE_PUBLIC_URL: ${MERCURE_PUBLIC_URL}
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
